-- update_schema1.sql: Migration for ORM-DB sync
-- Generated by AI assistant

-- === CREATE TABLES MISSING IN DB ===

CREATE TABLE IF NOT EXISTS property_features (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES projects(id) NOT NULL, -- ✅ In ORM
    name VARCHAR(100) NOT NULL, -- ✅ In ORM
    value VARCHAR(500) NOT NULL -- ✅ In ORM
);

CREATE TABLE IF NOT EXISTS property_images (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES projects(id) NOT NULL, -- ✅ In ORM
    url VARCHAR(500) NOT NULL, -- ✅ In ORM
    caption VARCHAR(200), -- ✅ In ORM
    is_primary BOOLEAN DEFAULT FALSE -- ✅ In ORM
);

CREATE TABLE IF NOT EXISTS property_amenities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES projects(id) NOT NULL, -- ✅ In ORM
    name VARCHAR(100) NOT NULL, -- ✅ In ORM
    description VARCHAR(500), -- ✅ In ORM
    category VARCHAR(100) NOT NULL -- ✅ In ORM
);

CREATE TABLE IF NOT EXISTS outreach_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id UUID REFERENCES customers(id) NOT NULL, -- ✅ In ORM
    name VARCHAR(100) NOT NULL, -- ✅ In ORM
    description VARCHAR(500), -- ✅ In ORM
    channel VARCHAR(50) NOT NULL, -- ✅ In ORM
    subject VARCHAR(200), -- ✅ In ORM
    body TEXT NOT NULL, -- ✅ In ORM
    variables JSON, -- ✅ In ORM
    is_active BOOLEAN DEFAULT TRUE, -- ✅ In ORM
    created_at TIMESTAMPTZ DEFAULT now(), -- ✅ In ORM
    updated_at TIMESTAMPTZ -- ✅ In ORM
);

CREATE TABLE IF NOT EXISTS scraping_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    config_id UUID REFERENCES scraping_configs(id) NOT NULL, -- ✅ In ORM
    source VARCHAR(50) NOT NULL, -- ✅ In ORM
    status VARCHAR(50) NOT NULL, -- ✅ In ORM
    location VARCHAR(100), -- ✅ In ORM
    property_type VARCHAR(50), -- ✅ In ORM
    items_scraped INTEGER DEFAULT 0, -- ✅ In ORM
    error_message TEXT, -- ✅ In ORM
    started_at TIMESTAMPTZ, -- ✅ In ORM
    completed_at TIMESTAMPTZ, -- ✅ In ORM
    created_at TIMESTAMPTZ DEFAULT now(), -- ✅ In ORM
    updated_at TIMESTAMPTZ -- ✅ In ORM
);

CREATE TABLE IF NOT EXISTS scraping_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id UUID REFERENCES scraping_jobs(id) NOT NULL, -- ✅ In ORM
    title VARCHAR(255) NOT NULL, -- ✅ In ORM
    description TEXT, -- ✅ In ORM
    price FLOAT, -- ✅ In ORM
    location VARCHAR(100), -- ✅ In ORM
    property_type VARCHAR(50), -- ✅ In ORM
    bedrooms INTEGER, -- ✅ In ORM
    bathrooms INTEGER, -- ✅ In ORM
    area FLOAT, -- ✅ In ORM
    images JSON, -- ✅ In ORM
    source_url VARCHAR(255), -- ✅ In ORM
    metadata JSON, -- ✅ In ORM
    created_at TIMESTAMPTZ DEFAULT now(), -- ✅ In ORM
    updated_at TIMESTAMPTZ -- ✅ In ORM
);

CREATE TABLE IF NOT EXISTS user_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) NOT NULL, -- ✅ In ORM
    refresh_token VARCHAR NOT NULL UNIQUE, -- ✅ In ORM
    jti VARCHAR NOT NULL UNIQUE, -- ✅ In ORM
    device_info JSON, -- ✅ In ORM
    ip_address VARCHAR, -- ✅ In ORM
    user_agent VARCHAR, -- ✅ In ORM
    is_active BOOLEAN DEFAULT TRUE, -- ✅ In ORM
    created_at TIMESTAMPTZ DEFAULT now(), -- ✅ In ORM
    last_activity TIMESTAMPTZ DEFAULT now(), -- ✅ In ORM
    expires_at TIMESTAMPTZ NOT NULL -- ✅ In ORM
);

-- === OUTREACH CAMPAIGNS TABLE ===
CREATE TABLE IF NOT EXISTS outreach_campaigns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id UUID REFERENCES customers(id) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    channel VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    scheduled_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    total_recipients INTEGER DEFAULT 0,
    successful_deliveries INTEGER DEFAULT 0,
    failed_deliveries INTEGER DEFAULT 0,
    campaign_metadata JSON,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ
);

-- === ALTER TABLES FOR MISSING COLUMNS ===

-- projects
ALTER TABLE projects ADD COLUMN IF NOT EXISTS property_type VARCHAR(50); -- ✅ In ORM
ALTER TABLE projects ADD COLUMN IF NOT EXISTS total_units INTEGER; -- ⚠️ Not found in ORM (check model)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS amenities JSON; -- ⚠️ Not found in ORM (check model)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS completion_date TIMESTAMPTZ; -- ⚠️ Not found in ORM (check model)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS address VARCHAR(200); -- ⚠️ Not found in ORM (check model)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS city VARCHAR(100); -- ⚠️ Not found in ORM (check model)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS state VARCHAR(100); -- ⚠️ Not found in ORM (check model)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20); -- ⚠️ Not found in ORM (check model)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS country VARCHAR(100); -- ⚠️ Not found in ORM (check model)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS latitude FLOAT; -- ⚠️ Not found in ORM (check model)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS longitude FLOAT; -- ⚠️ Not found in ORM (check model)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES users(id); -- ⚠️ Not found in ORM (check model)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_by UUID REFERENCES users(id); -- ⚠️ Not found in ORM (check model)

-- scraping_configs
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS enabled_sources JSON; -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS locations JSON; -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS property_types JSON; -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS price_range_min FLOAT; -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS price_range_max FLOAT; -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS max_pages_per_source INTEGER; -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS scraping_delay INTEGER; -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS max_retries INTEGER; -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS proxy_enabled BOOLEAN; -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS proxy_url VARCHAR(255); -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS user_agent VARCHAR(255); -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS auto_scrape_enabled BOOLEAN; -- ✅ In ORM
ALTER TABLE scraping_configs ADD COLUMN IF NOT EXISTS auto_scrape_interval INTEGER; -- ✅ In ORM

-- audit_logs
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS customer_id UUID REFERENCES customers(id); -- ⚠️ Not found in ORM (check model)
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS resource_type VARCHAR; -- ⚠️ Not found in ORM (check model)
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS resource_id UUID; -- ⚠️ Not found in ORM (check model)
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS details JSON; -- ⚠️ Not found in ORM (check model)

-- (Repeat for other tables as needed based on your ORM model definitions)

-- =========================
-- SUMMARY
-- =========================
-- Tables with new columns: projects, scraping_configs, audit_logs
-- Tables fully synced: property_features, property_images, property_amenities, outreach_templates, scraping_jobs, scraping_results, user_sessions
-- Columns still missing in ORM: See lines marked with ⚠️ above 